name: Build with Clang

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build project
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja -C build

      - name: Display build status
        if: always()
        run: echo "::set-output name=build_status::success"
