name: Build with GCC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Build project
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja -C build